### ISSUE TITLE
Tabs are not working in version 2.2.1 on 9.3 and 9.01

### ISSUE THREAD

**Issue by djewst** [ugo-quaisse/sitecore-author-toolbox#8]
**Describe the bug**
I enable tab section feature
I go to the content editor, load any item and don't see any tabs.

**To Reproduce**
1. Go to 'Content editor'
2. Click on 'any item'
3. See no tabs for any of the standard items. 

**Expected behavior**
See the tabs for the different standard item sections. I only see my custom fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/24729437/84384727-b2e2de00-abee-11ea-898e-67ae1c308546.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version Version 83.0.4103.61 (Official Build) (64-bit)

**Additional context**
It is in my custom client solutions.
I do see console errors:
Content Editor.aspx?sc_bw=1:1 Error handling response: TypeError: Cannot read property 'setAttribute' of null
    at chrome-extension://mckfcmcdbgkgffdknpkaihjigmcnnbco/js/modules/contenteditor.js:625:34

Sitecore Author Toolbox: Error in fetching your CD URL (https://93horizonsc.dev.local/en/?sc_site=website&sc_mode=normal), it might be a timeout, a mixed content error (if you are over https) or a settings issue, please check or log a ticket at https://github.com/ugo-quaisse/sitecore-author-toolbox/issues/new/choose

SitecoreWindow.js:183 Uncaught TypeError: ctl.className.indexOf is not a function
    at scWindow.hitTest (SitecoreWindow.js:183)
    at scWindow.mouseMove (SitecoreWindow.js:242)
    at HTMLBodyElement.onmousemove (Content Editor.aspx?sc_bw=1:65)

**Comment by ugo-quaisse** [comment]
@djewst Do you see that issue for any item or only in few items? If yes can you identify a pattern? for instance, items with only one section/tab etc...?
thank you

**Comment by djewst** [comment]
nope, I see it for every item, both out of the box Sitecore items and custom.
Found out if I uncheck 'standard fields' in view, I do get tabs for my custom sections. As soon as I check it again tabs are gone. I don't get to see the standard items at all

**Comment by ugo-quaisse** [comment]
@djewst  I just released 2.3 today with some changes on tabs that hopefully will fix your issue (not 100% sure as I cannot reproduce it)
Can you make sure you have 2.3 and give it another try?
Thank you!

**Comment by djewst** [comment]
I don't know if it was the update, or removing and reinstalling it on chrome, it is working now!
